// flow-typed signature: 6cbf6c45b170e9959455975bd67664f4
// flow-typed version: <<STUB>>/gatsby-image_v2.0.37/flow_v0.96.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-image' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gatsby-image/withIEPolyfill/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gatsby-image/index' {
  declare module.exports: $Exports<'gatsby-image'>;
}
declare module 'gatsby-image/index.js' {
  declare module.exports: $Exports<'gatsby-image'>;
}
declare module 'gatsby-image/withIEPolyfill/index.js' {
  declare module.exports: $Exports<'gatsby-image/withIEPolyfill/index'>;
}
