export { getWindowWidth } from './getWindowWidth'
export { isMobile } from './isMobile'
export { getImagesFromEdges } from './getImagesFromEdges'
export { createImageLabel } from './createImageLabel'
export { shuffleArray } from './shuffleArray'
